export const EDITORIAL_PROFILE_IDS: readonly string[];
export const EDITORIAL_ROUNDING: readonly string[];
export const ANNOTATION_KINDS: readonly string[];
export const DATA_GRAPHIC_KINDS: readonly string[];
export function stableEditorialHash(value: unknown): string;
export function secondsToFrame(seconds: number, fps: number, rounding?: string): number;
export function frameToSeconds(frame: number, fps: number): number;
export function resolvedEditPointFor(editorial: any, editPointId: string, sceneId?: string): any;
export function editPointFrameFor(editorial: any, editPointId: string, sceneId?: string): number;
export function editPointProgress(options: any): number;
export function measureEditorialText(text: string, fontSize: number, letterSpacing?: number): number;
export function wrapEditorialText(options: any): string[];
export function fitEditorialTypography(options: any): {
  fontSize: number;
  lines: string[];
  requiredHeight: number;
  overflow: boolean;
};
export function typographyRevealUnits(node: any, lines: string[]): any[];
export function resolveTypographyReveal(options: any): any[];
export function resolveTypographyEmphasis(options: any): any[];
export function resolveSemanticAnchor(options: any): {x: number; y: number} | null;
export function flattenEditorialAnchorNodes(nodes: any[], parent?: any): any[];
export function applyResponsiveDirectingPlan<T>(project: T): T;
export function resolveAnnotationRoute(options: any): any;
export function resolveDataDomain(node: any): [number, number];
export function formatDataValue(value: number, format?: any): string;
export function validateDataGraphicNode(node: any, location?: string): any[];
export function resolveDataState(options: any): any;
export function resolveEditorialSwitch(options: any): any;
export function lifecycleOpacity(options: any): number;
